# image will be published to ghcr.io/<user>/<name>
name: hyprepix
# description will be included in the image's metadata
description: This is my personal OS image.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/cosmic-silverblue-nvidia
image-version: "latest-amd64" # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system/hyprland
        destination: /
  - type: rpm-ostree
    repos:
      # - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%OS_VERSION%/atim-starship-fedora-%OS_VERSION%.repo
      #with bazzite they should not be required
      #  - https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-40.noarch.rpm
      #  - https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-40.noarch.rpm
    install:
      #Cancelled nvidia
      #- xorg-x11-server-Xwayland
      #- xorg-x11-drv-nvidia-cuda

      ##SDDM stuff
      - sddm
      - sddm-themes
      - qt5-qtgraphicaleffects
      - qt5-qtquickcontrols2
      - qt5-qtsvg
      # launcher
      - rofi-wayland
      - kvantum-qt5
      # environment
      - polkit
      - lxpolkit
      - xdg-user-dirs
      - dbus-tools
      - dbus-daemon
      - wl-clipboard
      - gnome-keyring
      - pavucontrol
      - playerctl
      - qt5-qtwayland
      - vulkan-validation-layers
      - vulkan-tools
      - google-noto-emoji-fonts
      - gnome-disk-utility
      - gparted

      # sound
      - wireplumber
      - pipewire
      - pamixer

      # networking
      - network-manager-applet
      - NetworkManager-openvpn
      - NetworkManager-openconnect
      - bluez
      - bluez-tools
      - blueman

      # file manager
      #- pcmanfm-qt
      #- xarchiver
      #- imv
      #- p7zip
      #- unrar-free
      #- akmod-nvidia
      - pipewire-alsa
      # screenshot
      #- slurp
      #- grim

      # display
      # - libva-nvidia-driver

      - wlr-randr
      - wlsunset
      - brightnessctl
      - swaylock
      - swayidle
      - kanshi

      # terminal
      - foot
      - fish

      # notifications
      - dunst

      # theme and GUI
      - adwaita-qt5
      - fontawesome-fonts-all
      - gnome-themes-extra
      - gnome-icon-theme
      - paper-icon-theme
      - breeze-icon-theme
      - papirus-icon-theme
      - kvantum
      - adw-gtk3-theme
      - adwaita-qt6
      - libadwaita-qt5
      - libadwaita-qt6

      ##Hyperland specific
      - hyprland
      - waybar
      - xdg-desktop-portal-hyprland
      - cpio
      - "gcc-c++"
      - cmake
      - meson
      - hyprcursor
      - hyprcursor-devel
      - tomlplusplus
      - tomlplusplus-devel
      ##base-nvidia
      #- nvidia-vaapi-backend
      - ffmpeg
      - gstreamer1-plugin-libav
      - gstreamer1-plugins-bad-free-extras
      - gstreamer1-vaapi

      #- brightnessctl
      # - micro
      # - starship
    remove:
      - docker-compose
      # example: removing firefox (in favor of the flatpak)
      # "firefox" is the main package, "firefox-langpacks" is a dependency
      # - firefox
      # - firefox-langpacks # also remove firefox dependency (not required for all packages, this is a special case)

  - type: default-flatpaks
    notify: true # Send notification after install/uninstall is finished (true/false)
    system:
      # If no repo information is specified, Flathub will be used by default
      # repo-url: https://dl.flathub.org/repo/flathub.flatpakrepo
      # repo-name: flathub
      # repo-title: "Flathub (system-wide)" # Optional; this sets the remote's user-facing name in graphical frontends like GNOME Software
      install:
        - org.ferdium.Ferdium
        # - org.mozilla.firefox
        # - org.gnome.Loupe
        # - one.ablaze.floorp//lightning # This is an example of flatpak which has multiple branches in selection (flatpak//branch).
      # Flatpak runtimes are not supported (like org.winehq.Wine//stable-23.08),
      # only normal flatpak applications are (like Floorp Lightning web browser in this example).
      # Installing different branches of the same Flatpak is not supported.
      remove:
      # - org.gnome.eog
  - type: script
    scripts:
      - settheming.sh
      ##hyprland-scripts
      - sethyprlandwaybarmodules.sh
      #- "sudo rpm-ostree kargs --append=rd.driver.blacklist=nouveau --append=modprobe.blacklist=nouveau --append=nvidia-drm.modeset=1 # this might not be needed at some point when ostree systems will support the standard way to specify this."
      #- hyprplugins.sh
      ##SDDM
      #- setsddmtheming.sh
  - type: systemd
    system:
      enabled:
        - sddm-boot.service

  - type: signing # this sets up the proper policy & signing files for signed images to work fully
